name: Archives

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install zip
      run: sudo apt-get install zip

    - name: Archive llava-benchmark files
      run: |
        zip -r llava-benchmark_${{ github.sha }}.zip .


    - name: Upload archived files
      uses: actions/upload-artifact@v4
      with:
        name: llava-benchmark_${{ github.sha }}.zip
        path: llava-benchmark_${{ github.sha }}.zip
