name: Build and deploy documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create tmp _build and _static folders
        run: mkdir -p docs/{_build,_static}
        

      - name: Install Sphinx dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme

      - name: Build HTML pages with Sphinx
        run: |
          cd docs
          make html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html 
        